name: Integration

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    name: Test
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup go
        uses: actions/setup-go@v5
        with:
          go-version-file: "go.mod"
          cache: true

      - name: Test
        run: go test -coverprofile=coverage.txt -covermode=atomic ./...

      - name: Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage.txt

  build:
    name: Build
    runs-on: ubuntu-22.04
    needs:
      - test
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup go
        uses: actions/setup-go@v5
        with:
          go-version-file: "go.mod"
          cache: true

      - name: Build Releases
        uses: goreleaser/goreleaser-action@v6.0.0
        with:
          version: "~> v2"
          args: release --clean --snapshot
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  automerge:
    name: Merge Automatically
    needs: [test, build]
    runs-on: ubuntu-20.04
    if: ${{ github.actor == 'dependabot[bot]' }}

    permissions:
      pull-requests: write
      contents: write

    steps:
      - name: Obtain Access Token
        id: acces_token
        run: |
          TOKEN="$(npx obtain-github-app-installation-access-token ci ${{ secrets.SYSTEMLI_APP_CREDENTIALS_TOKEN }})"
          echo "token=$TOKEN" >> $GITHUB_OUTPUT

      - name: Merge
        uses: fastify/github-action-merge-dependabot@v3
        with:
          github-token: ${{ steps.acces_token.outputs.token }}
